# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'authApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for authApp
    pod ‘gRPC-Swift’, ‘~> 1.5.0’ # Latest at the time of writing
    pod ‘gRPC-Swift-Plugins’

  target 'authAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'authAppUITests' do
    # Pods for testing
  end

end
