# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'testing_gRPC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod ‘gRPC-Swift’, ‘~> 1.5.0’ # Latest at the time of writing
  pod ‘gRPC-Swift-Plugins’
  # Pods for testing_gRPC

  target 'testing_gRPCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testing_gRPCUITests' do
    # Pods for testing
  end

end
